image: maven:3.9.6-eclipse-temurin-21

stages:
  - test
  - build-jar
  - docker-build-nginx
  - docker-build-app

unit_tests:
  stage: test
  before_script:
    - cd report-system
  script:
    - mvn test

build_jar:
  stage: build-jar
  before_script:
    - cd report-system
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - report-system/target/*.jar

build_app_image:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: docker-build-app
  before_script:
    - cd report-system
  script:
    - docker build -t spring-app .

build_nginx_image:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: docker-build-nginx
  before_script:
    - cd report-system/nginx
  script:
    - docker build -t nginx-image .