services:
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
     - "80:80"
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
  app:
    image: spring-app
    container_name: application
    depends_on:
      - db
    expose:
      - "8080"
    env_file:
      - .env
