events {}

http {

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;


    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;

        }

        location /api/ {
            limit_req zone=api_limit burst=10 nodelay;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_pass http://app:8080;
        }

    }
}